### PR TITLE
Separate relational definitions into a separate module

### LINKED ISSUE #11: Circular dependency on generated schema
Simply separate all definitions into a single module

This issue raised from these comments:
https://github.com/farreldarian/prisma-generator-drizzle/issues/1#issuecomment-1873605305
https://github.com/farreldarian/prisma-generator-drizzle/issues/1#issuecomment-1873616242

### PR DESCRIPTION
**Pull request by farreldarian**
Resolves #11

### CODE REVIEW

**Comment by farreldarian** [comment]
Hi @octalpixel, I just added [the PR](https://github.com/farreldarian/prisma-generator-drizzle/pull/13) to properly fix the circular dependencies. Could you please confirm by using [`0.5.4-9955142`](https://www.npmjs.com/package/prisma-generator-drizzle/v/0.5.4-9955142) resolves the issue?


Regarding your solutions:

> Have a flag to output everything to one file. (Fixes the require cycle for React Native projects)

I think It'd be an extra work to sort the const definitions whoever should be declared first or later. Also it should be better for the editor's performance

> Have a flag to output relationship to another file

This PR will make that as the default

> Flag to only generate relationships (This can actually be a good starting point to learn about how to make relationships with Drizzle as well)

The main focus currently is to use Drizzle from Prisma schema — a drop-in replacement for their prisma client engine. However please feel free to raise an issue describing the motivation and examples to see how many people upvote this.

**Comment by Scalahansolo** [comment]
While messing around with the lib last night I noticed a bug that Im not sure would be solved by this.

When a model references itself as a relation like....

```
model Post {
    subPosts    Post[]
}
```

It seems like the generated file tries to import itself for the relation.

**Comment by farreldarian** [comment]
> While messing around with the lib last night I noticed a bug that Im not sure would be solved by this.
> 
> When a model references itself as a relation like....
> 
> ```
> model Post {
>     subPosts    Post[]
> }
> ```
> 
> It seems like the generated file tries to import itself for the relation.

Sorry, I've just had the chance to check, I just added the test for self-reference and it works just fine, also I think this PR isn't related to the problem. Could you please provide a reproductive case where it fails?

**Comment by Scalahansolo** [comment]
In the cases of my schema where I notice the issue is definitely in the few places where a model has a self referencing relation. So if those relations are now broken out into their own files, I would expect that to be working properly.

**Comment by farreldarian** [comment]
> In the cases of my schema where I notice the issue is definitely in the few places where a model has a self referencing relation. So if those relations are now broken out into their own files, I would expect that to be working properly.

So this is the test schema that I added

https://github.com/farreldarian/prisma-generator-drizzle/blob/6c92c8923187dfd01c707ebb9a2d5e601dcf60ac/packages/usage/prisma/schema.prisma#L59
```prisma
model SelfReference {
  id String @id
  referringManyId String?
  referringMany   SelfReference?  @relation("SelfReference_referringMany", fields: [referringManyId], references: [id])
  referredMany    SelfReference[] @relation("SelfReference_referringMany")
  referringUniqueId String?        @unique
  referringUnique   SelfReference? @relation("SelfReference_referringUnique", fields: [referringUniqueId], references: [id])
  referredUnique    SelfReference? @relation("SelfReference_referringUnique")
}
```

As well as the test: https://github.com/farreldarian/prisma-generator-drizzle/blob/pgd-11-circular-dependency-on-generated-schema/packages/usage/tests/shared/testSelfReferring.ts

All is working perfectly, do you encounter a specific error that I could look at?

**Comment by Scalahansolo** [comment]
Hey, sorry for the delay I'll take a look at if the new version solves what I was seeing.

**Comment by Scalahansolo** [comment]
@farreldarian I just ran a quick test with the separated relations with the 0.5.4 version you gave me and the issue I was seeing is now gone

**Comment by farreldarian** [comment]
> Quick test with the separated relations with the 0.5.4 version you gave me and the issue I was seeing is now gone

Awesome! I'm just gonna merge this now, if anything comes up please feel free to raise a new issue

**Pull request merged**
